apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - image: localhost:5000/sample-app
        name: app
        imagePullPolicy: IfNotPresent